In [5]:
!pip install numpy
!/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -m pip install --upgrade pip

  Using cached numpy-1.22.2.zip (11.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  error: subprocess-exited-with-error
  
  × Building wheel for numpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [175 lines of output]
      Running from numpy source directory.
      Cythonizing sources
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      /private/var/folders/5_/wb7mz7sd70q1prflth0cmd0m0000gn/T/pip-install-qsjjltnf/numpy_3b4fcfce29424b4a8dd4c2470336da86/tools/cythonize.py:63: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
        from distutils.version import LooseVersion
      Processing numpy/random/_bounded_integers.pyx.in
      Processing numpy/random/_sfc64.pyx
      Processing numpy/random/_mt19937.pyx
      Pro

In [2]:
import random 
import numpy as np 
import tensorflow as tf 
import matplotlib.pyplot as plt 

ModuleNotFoundError: No module named 'numpy'

In [2]:
N_BATCH = 16
N_EPOCHS = 10 
N_MARGIN = 1 

In [6]:
(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data()

In [10]:
train_images, val_images = train_images[:30000], train_images[30000:]
train_labels, val_labels = train_labels[:30000], train_labels[30000:]

In [4]:
def make_pairs(image, label):
    
    num_classes = max(label) + 1 
    digit_idx = [np.where(label == i)[0] for i in range(num_classes)]
    
    pairs = [] 
    labels = [] 
    
    for idx in range(len(image)):
        
        # add maching example 
        x1 = image[idx]
        y1 = label[idx]
        
        x2 = image[random.choice(digit_idx[y1])]
        
        pairs += [[x1, x2]]
        labels += [1]
        
        # add non-matching example
        y2 = random.randint(0, num_classes-1)
        while y2 == y1:
            y2 = random.randint(0, num_classes-1)
            
        x2 = image[random.choice(digit_idx[y2])]
        
        pairs += [[x1, x2]]
        labels += [0]
        
    return np.array(pairs), np.array(labels).astype('float32')
        
        

In [11]:
pairs_train, labels_train = make_pairs(train_images, train_labels)
pairs_val, labels_val = make_pairs(val_images, val_labels)
pairs_test, labels_test = make_pairs(test_images, test_labels)

In [9]:
num_classes = max(train_labels) + 1 
digit_idx = [np.where(train_labels == i)[0] for i in range(num_classes)]
# num_classes
digit_idx

[array([    1,    21,    34, ..., 59952, 59972, 59987], dtype=int64),
 array([    3,     6,     8, ..., 59979, 59984, 59994], dtype=int64),
 array([    5,    16,    25, ..., 59983, 59985, 59991], dtype=int64),
 array([    7,    10,    12, ..., 59978, 59980, 59996], dtype=int64),
 array([    2,     9,    20, ..., 59943, 59951, 59975], dtype=int64),
 array([    0,    11,    35, ..., 59968, 59993, 59997], dtype=int64),
 array([   13,    18,    32, ..., 59982, 59986, 59998], dtype=int64),
 array([   15,    29,    38, ..., 59963, 59977, 59988], dtype=int64),
 array([   17,    31,    41, ..., 59989, 59995, 59999], dtype=int64),
 array([    4,    19,    22, ..., 59973, 59990, 59992], dtype=int64)]